-- posts
drop table if exists posts cascade;

create table posts
(
    id      bigint generated by default as identity,
    title   varchar(500) not null,
    author  varchar(255),
    content TEXT         not null,
    primary key (id)
);
