-- posts
drop table if exists posts_springboot_aws_solo cascade;

create table posts_springboot_aws_solo
(
    id      bigint generated by default as identity,
    title   varchar(500) not null,
    author  varchar(255),
    content TEXT         not null,
    primary key (id)
);
